The_Labinator/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^labs/', include('labs.urls')),
    url(r'^testLab/', include('testLab.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^myapp/', include('myapp.urls')),
    url(r'^admin/', admin.site.urls),
]

labs/urls.py
from django.conf.urls import patterns, url
from labs import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^test', views.test, name='test')
]

myapp/urls.py
from django.conf.urls import url
from myapp.views import AuthorCreate, AuthorUpdate, AuthorDelete

urlpatterns = [
    url(r'author/add/$', AuthorCreate.as_view(), name='author-add'),
    url(r'author/(?P<pk>[0-9]+)/$', AuthorUpdate.as_view(), name='author-update'),
    url(r'author/(?P<pk>[0-9]+)/delete/$', AuthorDelete.as_view(), name='author-delete'),
]

polls/urls.py
from django.conf.urls import patterns, url
from polls import views


app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^test$', views.TestView.as_view(), name='test'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^test/(?P<pk>[0-9]+)/$', views.LabView.as_view(), name='lab'),
    url(r'^test/(?P<lab_id>[0-9]+)/submit/$', views.submit, name='submit'),
    url(r'^test/(?P<pk>[0-9]+)/labresults/$', views.LabResultsView.as_view(), name='labresults'),
]

testLab/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index')
]

labs/models.py
from __future__ import unicode_literals

from django.db import models

myapp/models.py
from django.core.urlresolvers import reverse
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse('author-detail', kwargs={'pk': self.pk})

polls/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Lab(models.Model):
    lab_name = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    question = models.CharField(max_length=200)
    def __str__(self):
        return self.lab_name

class Submission(models.Model):
    lab = models.ForeignKey(Lab)
    student_name = models.CharField(max_length=200)
    student_email = models.EmailField(max_length=254)
    input_int = models.IntegerField()
    def __str__(self):
        return self.student_name

testLab/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Lab(models.Model):
    labName = models.CharField(max_length=200)
    dateCreated = models.DateTimeField('date published')
	labQuestion = models.CharField(max_length=200)
	def __str__(self):
        return self.labName
    def was_published_recently(self):
        return self.dateCreated >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'dateCreated'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

myapp/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass

labs/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.
def index(request):
	return HttpResponse("This is a placeholder for labs index")

def test(request):
	return HttpResponse("You're looking at question a test?.")

myapp/views.py
from myapp.forms import ContactForm
from django.views.generic.edit import FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from myapp.models import Author

class AuthorCreate(CreateView):
    model = Author
    fields = ['name']

class AuthorUpdate(UpdateView):
    model = Author
    fields = ['name']

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('author-list')

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from polls.models import Question, Lab
from django.template import loader
from django.views import generic


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('pub_date')[:5]


class TestView(generic.ListView):
    template_name = 'polls/test.html'
    context_object_name = 'latest_labs'

    def get_queryset(self):
        return Lab.objects.order_by('pub_date')[:5]



class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

class LabView(generic.DetailView):
    model = Lab
    template_name = 'polls/lab.html'


def submit(request, lab_id):
    lab = get_object_or_404(Lab, pk=lab_id)
    try:
        student_name = request.POST['student_name']
        student_email = request.POST['student_email']
        input_int = request.POST['input_int']
        input_int = int(input_int)
    except:
        return render(request, 'polls/test.html',{
            'lab': lab,
            'error_message':"Please enter another integer, this was not accepted",
        })
    else:
        lab.submission_set.create(student_name = student_name, student_email = student_email, input_int = input_int)
        return HttpResponseRedirect(reverse('polls:labresults', args=(lab.id,)))





class LabResultsView(generic.DetailView):
    model = Lab
    template_name = 'polls/labresults.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        newchoice_name = request.POST['newchoice_name']
        newchoice_votes = request.POST['newchoice_votes']
        newchoice_votes = int(newchoice_votes)
    except:
        return render(request, 'polls/detail.html',{
            'question': question,
            'error_message':"Improper Input.",
        })
    else:
        question.choice_set.create(choice_text = newchoice_name, votes = newchoice_votes)
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

testLab/views.py
from django.http import HttpResponse
import datetime

# Create your views here.

def index(request):
    now = datetime.datetime.now()
    html = "<html><body>It is now %s.</body></html>"
    return HttpResponse(html)

myapp/templates/myapp/author_confirm_delete.html
<h1> Hello World </h1>

myapp/templates/myapp/author_form.html
<h1> Hello World </h1>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}




<form action="{% url 'polls:vote' question.id %}" method="post">
  {% csrf_token %}
  Choice name: <input type="text" name="newchoice_name"><br>
  # of votes: <input type="text" name="newchoice_votes"><br>
  {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
  {% endfor %}
  <input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    <li><a href="{% url 'polls:test' %}"> Help me out here guys </a></li>

</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

polls/templates/polls/lab.html
<h1>{{ lab.lab_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:submit' lab.id %}" method="post">
  {% csrf_token %}
  {{lab.question}} <input type="text" name="input_int"><br>
	Student Name: <input type="text" name="student_name"><br>
	Student Email: <input type="text" name="student_email"><br>
	<input type="submit" value="Submit" />
</form>

polls/templates/polls/labresults.html
<ul>
{% for submission in lab.submission_set.all %}
    <li>{{ submission.student_name }} with {{ submission.student_email }} they give this many $#@^'s '{{ submission.input_int }}</li>
{% endfor %}
</ul>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<script>

// alert('Hello, World!')

</script>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

polls/templates/polls/test.html
{% if latest_labs %}
<ul>
    {% for lab in latest_labs %}
    <li><a href="{% url 'polls:lab' lab.id %}">{{ lab.lab_name }}</a></li>
    {% endfor %}

</ul>
{% else %}
<p>Failed to get available labs</p>
{% endif %}